---
title: "Lope et Rotrou"
author: "Miguel Betti"
date: "19/09/2022"
output: html_document
---

#J'installe les librairies et les packages nécessaires: knitr, leaflet, etc.
```{r, setup, fig.show=hold, fig.margin=TRUE}
if(!require("knitr")){
  install.packages("knitr")
  library(knitr)
}
knitr::opts_chunk$set(echo = TRUE, fig.width=20)
```

```{r, warning=FALSE, results='hide'}
if(!require("leaflet")){
  install.packages("leaflet")
  library(leaflet)
}
if(!require("sp")){
  install.packages("sp")
  library(sp)
}
if(!require("rgdal")){
  install.packages("rgdal")
  library(rgdal)
}
if(!require("RColorBrewer")){
  install.packages("RColorBrewer")
  library(RColorBrewer)
}
if(!require("htmlwidgets")){
  install.packages("htmlwidgets")
  library(htmlwidgets)
}
if(!require("htmltools")){
  install.packages("htmltools")
  library(htmltools)
}
if(!require("leaflet.extras")){
  install.packages("leaflet.extras")
  library(leaflet.extras)
}
if(!require("geojsonio")){
  install.packages("geojsonio")
  library(geojsonio)
}
if(!require("geojsonlint")){
  install.packages("geojsonlint")
  library(geojsonlint)
}
if(!require("rjson")){
  install.packages("rjson")
  library(rjson)
}
if(!require("leaftime")){
  install.packages("leaftime")
  library(leaftime)
}

```

#Je charge les données de travail: les noms des lieux issus des pièces de Lope de Vega et des adaptations de Jean de Rotrou
```{r}
setwd("/Users/miguel/Desktop/Cartographie/CARTE")
```


```{r, results='hide'}
sortija_olvido  <- read.csv("DATA/LOPE/sortija_olvido.csv")
sortija_olvido$lng <- as.numeric(sortija_olvido$lng)
sortija_olvido$lat <- as.numeric(sortija_olvido$lat)
```

```{r, results='hide'}
ramilletes_madrid  <- read.csv("DATA/LOPE/ramilletes_madrid.csv")
ramilletes_madrid$lng <- as.numeric(ramilletes_madrid$lng)
ramilletes_madrid$lat <- as.numeric(ramilletes_madrid$lat)
```

```{r, results='hide'}
ocasion_perdida  <- read.csv("DATA/LOPE/ocasion_perdida.csv")
ocasion_perdida$lng <- as.numeric(ocasion_perdida$lng)
ocasion_perdida$lat <- as.numeric(ocasion_perdida$lat)
```

```{r, results='hide'}
poder_amor  <- read.csv("DATA/LOPE/poder_amor.csv")
poder_amor$lng <- as.numeric(poder_amor$lng)
poder_amor$lat <- as.numeric(poder_amor$lat)
```

```{r, results='hide'}
mirad_alabais  <- read.csv("DATA/LOPE/mirad_alabais.csv")
mirad_alabais$lng <- as.numeric(mirad_alabais$lng)
mirad_alabais$lat <- as.numeric(mirad_alabais$lat)
```

```{r, results='hide'}
villana_getafe  <- read.csv("DATA/LOPE/villana_getafe.csv")
villana_getafe$lng <- as.numeric(villana_getafe$lng)
villana_getafe$lat <- as.numeric(villana_getafe$lat)
```

```{r, results='hide'}
hermosa_alfreda  <- read.csv("DATA/LOPE/hermosa_alfreda.csv")
hermosa_alfreda$lng <- as.numeric(hermosa_alfreda$lng)
hermosa_alfreda$lat <- as.numeric(hermosa_alfreda$lat)
```

```{r, results='hide'}
laura_perseguida  <- read.csv("DATA/LOPE/laura_perseguida.csv")
laura_perseguida$lng <- as.numeric(laura_perseguida$lng)
laura_perseguida$lat <- as.numeric(laura_perseguida$lat)
```

```{r, results='hide'}
fingido_verdadero  <- read.csv("DATA/LOPE/fingido_verdadero.csv")
fingido_verdadero$lng <- as.numeric(fingido_verdadero$lng)
fingido_verdadero$lat <- as.numeric(fingido_verdadero$lat)
```

```{r, results='hide'}
mudanza_fortuna  <- read.csv("DATA/LOPE/mudanza_fortuna.csv")
mudanza_fortuna$lng <- as.numeric(mudanza_fortuna$lng)
mudanza_fortuna$lat <- as.numeric(mudanza_fortuna$lat)
```

```{r, results='hide'}
lope_cardona  <- read.csv("DATA/LOPE/lope_cardona.csv")
lope_cardona$lng <- as.numeric(lope_cardona$lng)
lope_cardona$lat <- as.numeric(lope_cardona$lat)
```

```{r, results='hide'}
bague_oubli  <- read.csv("DATA/ROTROU/bague_oubli.csv")
bague_oubli$lng <- as.numeric(bague_oubli$lng)
bague_oubli$lat <- as.numeric(bague_oubli$lat)
```

```{r, results='hide'}
celiane  <- read.csv("DATA/ROTROU/celiane.csv")
celiane$lng <- as.numeric(celiane$lng)
celiane$lat <- as.numeric(celiane$lat)
```

```{r, results='hide'}
occasions_perdues  <- read.csv("DATA/ROTROU/occasions_perdues.csv")
occasions_perdues$lng <- as.numeric(occasions_perdues$lng)
occasions_perdues$lat <- as.numeric(occasions_perdues$lat)
```

```{r, results='hide'}
heureuse_constance  <- read.csv("DATA/ROTROU/heureuse_constance.csv")
heureuse_constance$lng <- as.numeric(heureuse_constance$lng)
heureuse_constance$lat <- as.numeric(heureuse_constance$lat)
```

```{r, results='hide'}
diane  <- read.csv("DATA/ROTROU/diane.csv")
diane$lng <- as.numeric(diane$lng)
diane$lat <- as.numeric(diane$lat)
```

```{r, results='hide'}
belle_alphrede  <- read.csv("DATA/ROTROU/belle_alphrede.csv")
belle_alphrede$lng <- as.numeric(belle_alphrede$lng)
belle_alphrede$lat <- as.numeric(belle_alphrede$lat)
```

```{r, results='hide'}
laure_persecutee  <- read.csv("DATA/ROTROU/laure_persecutee.csv")
laure_persecutee$lng <- as.numeric(laure_persecutee$lng)
laure_persecutee$lat <- as.numeric(laure_persecutee$lat)
```


```{r, results='hide'}
veritable_genest  <- read.csv("DATA/ROTROU/veritable_genest.csv")
veritable_genest$lng <- as.numeric(veritable_genest$lng)
veritable_genest$lat <- as.numeric(veritable_genest$lat)
```

```{r, results='hide'}
cosroes  <- read.csv("DATA/ROTROU/cosroes.csv")
cosroes$lng <- as.numeric(cosroes$lng)
cosroes$lat <- as.numeric(cosroes$lat)
```

```{r, results='hide'}
lope_cardone  <- read.csv("DATA/ROTROU/lope_cardone.csv")
lope_cardone$lng <- as.numeric(lope_cardone$lng)
lope_cardone$lat <- as.numeric(lope_cardone$lat)
```


#Je prépare la carte
```{r}
#J'ajoute un fond de carte et je définis son point central
map <- leaflet(df) %>%
  addProviderTiles(providers$Esri.NatGeoWorldMap)%>% 
  setView(lng = -40, lat = 40, zoom =2.4)   %>%
  
  #J'ajoute les points issus des pièces, importées précédemment, et je leur attribue la couleur       (rouge pour les pièces de Lope, bleu pour celles de Rotrou), la taille et l'opacité
  addCircleMarkers(lng = sortija_olvido$lng, 
                   lat = sortija_olvido$lat,
                   group = "La sortija del olvido",
                   color = "red",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(sortija_olvido$obra, ":", sortija_olvido$lugar,",",
                                  sortija_olvido$menciones)) %>%
  
  addCircleMarkers(lng = ramilletes_madrid$lng, 
                   lat = ramilletes_madrid$lat,
                   group = "Ramilletes de Madrid",
                   color = "red",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(ramilletes_madrid$obra, ":", ramilletes_madrid$lugar,",",
                                  ramilletes_madrid$menciones)) %>%
  
  addCircleMarkers(lng = ocasion_perdida$lng, 
                   lat = ocasion_perdida$lat,
                   group = "La ocasión perdida",
                   color = "red",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(ocasion_perdida$obra, ":", ocasion_perdida$lugar,",",
                                  ocasion_perdida$menciones)) %>%
  
    addCircleMarkers(lng = poder_amor$lng, 
                   lat = poder_amor$lat,
                   group = "El poder vencido...",
                   color = "red",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(poder_amor$obra, ":", poder_amor$lugar,",",
                                  poder_amor$menciones)) %>%
  
  addCircleMarkers(lng = mirad_alabais$lng, 
                   lat = mirad_alabais$lat,
                   group = "Mirad a quién alabáis",
                   color = "red",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(mirad_alabais$obra, ":", mirad_alabais$lugar,",",
                                  mirad_alabais$menciones)) %>%
  
  addCircleMarkers(lng = villana_getafe$lng, 
                   lat = villana_getafe$lat,
                   group = "La villana de Getafe",
                   color = "red",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(villana_getafe$obra, ":", villana_getafe$lugar,",",
                                  villana_getafe$menciones)) %>%
  
  addCircleMarkers(lng = hermosa_alfreda$lng, 
                     lat = hermosa_alfreda$lat,
                     group = "La hermosa Alfreda",
                     color = "red",
                     weight=1,
                     fillOpacity = 0.5,
                     label = ~paste(hermosa_alfreda$obra, ":", hermosa_alfreda$lugar,",",
                                    hermosa_alfreda$menciones)) %>%
  
  addCircleMarkers(lng = laura_perseguida$lng, 
                   lat = laura_perseguida$lat,
                   group = "Laura perseguida",
                   color = "red",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(laura_perseguida$obra, ":", laura_perseguida$lugar,",",
                                  laura_perseguida$menciones)) %>%
  
  addCircleMarkers(lng = fingido_verdadero$lng, 
                   lat = fingido_verdadero$lat,
                   group = "Lo fingido verdadero",
                   color = "red",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(fingido_verdadero$obra, ":", fingido_verdadero$lugar,",",
                                  fingido_verdadero$menciones)) %>%
  
  addCircleMarkers(lng = mudanza_fortuna$lng, 
                   lat = mudanza_fortuna$lat,
                   group = "Las mudanzas de fortuna...",
                   color = "red",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(mudanza_fortuna$obra, ":", mudanza_fortuna$lugar,",",
                                  mudanza_fortuna$menciones)) %>%
  
   addCircleMarkers(lng = lope_cardona$lng, 
                   lat = lope_cardona$lat,
                   group = "Don Lope de Cardona",
                   color = "red",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(lope_cardona$obra, ":", lope_cardona$lugar,",",
                                  lope_cardona$menciones)) %>%

  addCircleMarkers(lng = bague_oubli$lng, 
                   lat = bague_oubli$lat,
                   group = "La Bague de l'oubli",
                   color = "blue",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(bague_oubli$obra, ":", bague_oubli$lugar,",",
                                  bague_oubli$menciones)) %>%
  
  addCircleMarkers(lng = celiane$lng, 
                   lat = celiane$lat,
                   group = "La Céliane",
                   color = "blue",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(celiane$obra, ":", celiane$lugar,",",
                                  celiane$menciones)) %>%
  
  addCircleMarkers(lng = occasions_perdues$lng, 
                   lat = occasions_perdues$lat,
                   group = "Les Occasions perdues",
                   color = "blue",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(occasions_perdues$obra, ":", occasions_perdues$lugar,",",
                                  occasions_perdues$menciones)) %>%
  
    addCircleMarkers(lng = heureuse_constance$lng, 
                   lat = heureuse_constance$lat,
                   group = "L'Heureuse Constance",
                   color = "blue",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(heureuse_constance$obra, ":", heureuse_constance$lugar,",",
                                  heureuse_constance$menciones)) %>%

  
  addCircleMarkers(lng = diane$lng, 
                   lat = diane$lat,
                   group = "La Diane",
                   color = "blue",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(diane$obra, ":", diane$lugar,",",
                                  diane$menciones)) %>%
  
  addCircleMarkers(lng = belle_alphrede$lng, 
                     lat = belle_alphrede$lat,
                     group = "La Belle Alphrède",
                     color = "blue",
                     weight=1,
                     fillOpacity = 0.5,
                     label = ~paste(belle_alphrede$obra, ":", belle_alphrede$lugar,",",
                                    belle_alphrede$menciones)) %>%
  
  addCircleMarkers(lng = laure_persecutee$lng, 
                   lat = laure_persecutee$lat,
                   group = "Laure persecutée",
                   color = "blue",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(laure_persecutee$obra, ":", laure_persecutee$lugar,",",
                                  laure_persecutee$menciones)) %>%
  
  addCircleMarkers(lng = veritable_genest$lng, 
                   lat = veritable_genest$lat,
                   group = "Le véritable Saint-Genest",
                   color = "blue",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(veritable_genest$obra, ":", veritable_genest$lugar,",",
                                  veritable_genest$menciones)) %>%
  
  addCircleMarkers(lng = cosroes$lng, 
                   lat = cosroes$lat,
                   group = "Cosroès",
                   color = "blue",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(cosroes$obra, ":", cosroes$lugar,",",
                                  cosroes$menciones)) %>%
  
   addCircleMarkers(lng = lope_cardone$lng, 
                   lat = lope_cardone$lat,
                   group = "Don Lope de Cardone",
                   color = "blue",
                   weight=1,
                   fillOpacity = 0.5,
                   label = ~paste(lope_cardone$obra, ":", lope_cardone$lugar,",",
                                  lope_cardone$menciones)) %>%
  
  #J'ajoute une fonction reset, qui permet de reactiver setView()
   addResetMapButton() %>%
  
  #J'ajoute un panneau de contrôle pour pouvoir selectionner les différentes options, des légendes,   et je définis leur position sur la carte 
  addLayersControl(baseGroups = c("Obras"),
                   
                   overlayGroups = c("La Bague de l'oubli", "La sortija del olvido", 
                         "La Céliane", "Ramilletes de Madrid",
                         "Les Occasions perdues", "La ocasión perdida",
                         "L'Heureuse Constance", "Mirad a quién alabáis", "El poder vencido...",
                         "La Diane", "La villana de Getafe",
                         "La Belle Alphrède", "La hermosa Alfreda",
                         "Laure persecutée", "Laura perseguida",
                         "Le véritable Saint-Genest", "Lo fingido verdadero",
                         "Cosroès","Las mudanzas de fortuna...",
                         "Don Lope de Cardone", "Don Lope de Cardona"),
                   
                   options = layersControlOptions(collapsed = TRUE))%>%

  
     addLegend(position = "bottomleft", 
              labels = c("Obras de Lope de Vega",
                         "Obras de Rotrou"), 
              
                
              colors = c("red",
                         "blue"),
              
              title = "Adaptaciones:")
  
map
```

#Je sauvegarde ma carte en format html
```{r}
saveWidget(map, file="Lope_Rotrou.html")
browseURL("Lope_Rotrou.html")
```




