---
title: "Lope"
author: "Miguel Betti"
date: "01/09/2022"
output: html_document
---


```{r, setup, fig.show=hold, fig.margin=TRUE}
if(!require("knitr")){
  install.packages("knitr")
  library(knitr)
}
knitr::opts_chunk$set(echo = TRUE, fig.width=20)
```

```{r, warning=FALSE, results='hide'}
if(!require("leaflet")){
  install.packages("leaflet")
  library(leaflet)
}
if(!require("sp")){
  install.packages("sp")
  library(sp)
}
if(!require("rgdal")){
  install.packages("rgdal")
  library(rgdal)
}
if(!require("RColorBrewer")){
  install.packages("RColorBrewer")
  library(RColorBrewer)
}
if(!require("htmlwidgets")){
  install.packages("htmlwidgets")
  library(htmlwidgets)
}
if(!require("htmltools")){
  install.packages("htmltools")
  library(htmltools)
}
if(!require("leaflet.extras")){
  install.packages("leaflet.extras")
  library(leaflet.extras)
}
if(!require("geojsonio")){
  install.packages("geojsonio")
  library(geojsonio)
}
if(!require("geojsonlint")){
  install.packages("geojsonlint")
  library(geojsonlint)
}
if(!require("rjson")){
  install.packages("rjson")
  library(rjson)
}
if(!require("leaftime")){
  install.packages("leaftime")
  library(leaftime)
}

```

```{r}
setwd("/Users/miguel/Desktop/Cartographie/CARTE")
```


```{r, results='hide'}
sortija_olvido  <- read.csv("DATA/LOPE/sortija_olvido.csv")
sortija_olvido$lng <- as.numeric(sortija_olvido$lng)
sortija_olvido$lat <- as.numeric(sortija_olvido$lat)
```

```{r, results='hide'}
ramilletes_madrid  <- read.csv("DATA/LOPE/ramilletes_madrid.csv")
ramilletes_madrid$lng <- as.numeric(ramilletes_madrid$lng)
ramilletes_madrid$lat <- as.numeric(ramilletes_madrid$lat)
```

```{r, results='hide'}
ocasion_perdida  <- read.csv("DATA/LOPE/ocasion_perdida.csv")
ocasion_perdida$lng <- as.numeric(ocasion_perdida$lng)
ocasion_perdida$lat <- as.numeric(ocasion_perdida$lat)
```

```{r, results='hide'}
poder_amor  <- read.csv("DATA/LOPE/poder_amor.csv")
poder_amor$lng <- as.numeric(poder_amor$lng)
poder_amor$lat <- as.numeric(poder_amor$lat)
```

```{r, results='hide'}
mirad_alabais  <- read.csv("DATA/LOPE/mirad_alabais.csv")
mirad_alabais$lng <- as.numeric(mirad_alabais$lng)
mirad_alabais$lat <- as.numeric(mirad_alabais$lat)
```

```{r, results='hide'}
villana_getafe  <- read.csv("DATA/LOPE/villana_getafe.csv")
villana_getafe$lng <- as.numeric(villana_getafe$lng)
villana_getafe$lat <- as.numeric(villana_getafe$lat)
```

```{r, results='hide'}
hermosa_alfreda  <- read.csv("DATA/LOPE/hermosa_alfreda.csv")
hermosa_alfreda$lng <- as.numeric(hermosa_alfreda$lng)
hermosa_alfreda$lat <- as.numeric(hermosa_alfreda$lat)
```

```{r, results='hide'}
laura_perseguida  <- read.csv("DATA/LOPE/laura_perseguida.csv")
laura_perseguida$lng <- as.numeric(laura_perseguida$lng)
laura_perseguida$lat <- as.numeric(laura_perseguida$lat)
```

```{r, results='hide'}
fingido_verdadero  <- read.csv("DATA/LOPE/fingido_verdadero.csv")
fingido_verdadero$lng <- as.numeric(fingido_verdadero$lng)
fingido_verdadero$lat <- as.numeric(fingido_verdadero$lat)
```

```{r, results='hide'}
mudanza_fortuna  <- read.csv("DATA/LOPE/mudanza_fortuna.csv")
mudanza_fortuna$lng <- as.numeric(mudanza_fortuna$lng)
mudanza_fortuna$lat <- as.numeric(mudanza_fortuna$lat)
```

```{r, results='hide'}
lope_cardona  <- read.csv("DATA/LOPE/lope_cardona.csv")
lope_cardona$lng <- as.numeric(lope_cardona$lng)
lope_cardona$lat <- as.numeric(lope_cardona$lat)
```

```{r}
data_comedia <-read.csv("DATA/GENRE/Lope/comedia.csv")
icon_comedia <- makeAwesomeIcon(icon = "c", 
                                markerColor = "red",
                                iconColor = "black")
```


```{r}
data_drama <-read.csv("DATA/GENRE/Lope/drama.csv")
icon_drama <- makeAwesomeIcon(icon = "d", 
                                markerColor = "blue",
                                iconColor = "black")
```


```{r}

map <- leaflet(df) %>%
  addProviderTiles(providers$Esri.NatGeoWorldMap)%>% 
  setView(lng = -40, lat = 40, zoom =2.4)   %>%
  
  addCircleMarkers(lng = sortija_olvido$lng, 
                   lat = sortija_olvido$lat,
                   group = "La sortija del olvido",
                   color = "blue",
                   weight=1,
                   radius = ~sqrt(sortija_olvido$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(sortija_olvido$lugar,
                                  sortija_olvido$menciones)) %>%
  
  addCircleMarkers(lng = ramilletes_madrid$lng, 
                   lat = ramilletes_madrid$lat,
                   group = "Ramilletes de Madrid",
                   color = "purple",
                   weight=1,
                   radius = ~sqrt(ramilletes_madrid$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(ramilletes_madrid$lugar,
                                  ramilletes_madrid$menciones)) %>%
  
  addCircleMarkers(lng = ocasion_perdida$lng, 
                   lat = ocasion_perdida$lat,
                   group = "La ocasión perdida",
                   color = "green",
                   weight=1,
                   radius = ~sqrt(ocasion_perdida$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(ocasion_perdida$lugar,
                                  ocasion_perdida$menciones)) %>%
  
    addCircleMarkers(lng = poder_amor$lng, 
                   lat = poder_amor$lat,
                   group = "El poder vencido",
                   color = "yellow",
                   weight=1,
                   radius = ~sqrt(poder_amor$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(poder_amor$lugar,
                                  poder_amor$menciones)) %>%
  
  addCircleMarkers(lng = mirad_alabais$lng, 
                   lat = mirad_alabais$lat,
                   group = "Mirad a quién alabáis",
                   color = "orange",
                   weight=1,
                   radius = ~sqrt(mirad_alabais$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(mirad_alabais$lugar,
                                  mirad_alabais$menciones)) %>%
  
  addCircleMarkers(lng = villana_getafe$lng, 
                   lat = villana_getafe$lat,
                   group = "La villana de Getafe",
                   color = "white",
                   weight=1,
                   radius = ~sqrt(villana_getafe$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(villana_getafe$lugar,
                                  villana_getafe$menciones)) %>%
  
  addCircleMarkers(lng = hermosa_alfreda$lng, 
                     lat = hermosa_alfreda$lat,
                     group = "La hermosa Alfreda",
                     color = "black",
                     weight=1,
                     radius = ~sqrt(hermosa_alfreda$menciones) * 4,
                     fillOpacity = 0.5,
                     label = ~paste(hermosa_alfreda$lugar,
                                    hermosa_alfreda$menciones)) %>%
  
  addCircleMarkers(lng = laura_perseguida$lng, 
                   lat = laura_perseguida$lat,
                   group = "Laura perseguida",
                   color = "brown",
                   weight=1,
                   radius = ~sqrt(laura_perseguida$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(laura_perseguida$lugar,
                                  laura_perseguida$menciones)) %>%
  
  addCircleMarkers(lng = fingido_verdadero$lng, 
                   lat = fingido_verdadero$lat,
                   group = "Lo fingido verdadero",
                   color = "red",
                   weight=1,
                   radius = ~sqrt(fingido_verdadero$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(fingido_verdadero$lugar,
                                  fingido_verdadero$menciones)) %>%
  
  addCircleMarkers(lng = mudanza_fortuna$lng, 
                   lat = mudanza_fortuna$lat,
                   group = "Las mudanzas de fortuna",
                   color = "pink",
                   weight=1,
                   radius = ~sqrt(mudanza_fortuna$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(mudanza_fortuna$lugar,
                                  mudanza_fortuna$menciones)) %>%
  
   addCircleMarkers(lng = lope_cardona$lng, 
                   lat = lope_cardona$lat,
                   group = "Don Lope de Cardona",
                   color = "sienna",
                   weight=1,
                   radius = ~sqrt(lope_cardona$menciones) * 4,
                   fillOpacity = 0.5,
                   label = ~paste(lope_cardona$lugar,
                                  lope_cardona$menciones)) %>%

  
  addAwesomeMarkers(data = data_drama, 
                      data_drama$lng, 
                      data_drama$lat,
                      group = "Drama",
                      icon = icon_drama,
                      popup = ~paste("Lugar:", "<b>",data_drama$lugar,"</b>","<br>",
                                     "Menciones:", "<b>",data_drama$menciones,"</b>","<br>",
                                     "Obra:", "<b>",data_drama$obra,"</b>", "</b>","<br>",
                                     "Autor:", "<b>",data_drama$autor,"</b>","<br>",
                                     "Subgénero:", "<b>",data_drama$subgénero,"</b>","<br>",
                                      sep = " "
                                     )) %>%
    
  
    addAwesomeMarkers(data = data_comedia, 
                      data_comedia$lng, 
                      data_comedia$lat,
                      group = "Comedia",
                      icon = icon_comedia,
                      popup = ~paste("Lugar:", "<b>",data_comedia$lugar,"</b>","<br>",
                                     "Menciones:", "<b>",data_comedia$menciones,"</b>","<br>", 
                                     "Obra:", "<b>",data_comedia$obra,"</b>", "</b>","<br>",
                                     "Autor:", "<b>",data_comedia$autor,"</b>","<br>",
                                     "Subgénero:", "<b>",data_comedia$subgénero,"</b>","<br>",
                                     sep = " "
                                     )) %>%
  
  
  addResetMapButton() %>%
   
  addLayersControl(baseGroups = c("Comedias de Lope"),
                   
                   overlayGroups = c("La sortija del olvido", "Ramilletes de Madrid", "La ocasión perdida", "El poder vencido", "Mirad a quién alabáis", "La villana de Getafe", "La hermosa Alfreda", "Laura perseguida", "Lo fingido verdadero", "Las mudanzas de fortuna", "Don Lope de Cardona", "Drama", "Comedia"),
                   options = layersControlOptions(collapsed = TRUE)) %>%
  
                   
                    addLegend("bottomleft", 
              
              colors = c("trasparent"),

              labels=c("Mapa y extracción de datos: Miguel Betti - miguel.betti@unige.ch"),
             
              title="Lope en el mapa:") %>%
  

addLegend(position = "bottomleft", 
              labels = c("Drama",
                         "Comedia"), 
              
                
              colors = c("blue",
                         "red"),
              
              title = "Adaptaciones:")
  
map
```

```{r}
saveWidget(map, file="Lope_genre.html")
browseURL("Lope_genre.html")
```




